# Generated by Django 5.0.3 on 2024-06-13 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('watched_dt', models.DateTimeField(blank=True, verbose_name='Когда просмотрено')),
                ('dc', models.DateTimeField(auto_now_add=True, verbose_name='Когда создан')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.user', verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
            },
        ),
    ]
