# Generated by Django 5.0.3 on 2024-06-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='watched_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Когда просмотрено'),
        ),
    ]
