# Generated by Django 5.0.3 on 2024-04-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
