# Generated by Django 5.0.3 on 2024-05-22 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_group',
        ),
        migrations.RemoveField(
            model_name='room',
            name='name',
        ),
    ]
