# Generated by Django 5.0.3 on 2024-04-21 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_course', '0002_rename_admission_how_days_trainingcourse_days_admission_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
    ]
