# Generated by Django 5.0.3 on 2024-05-01 17:05

import training_course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_course', '0003_alter_lesson_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcourse',
            name='image',
            field=models.ImageField(blank=True, upload_to=training_course.models.image_directory_path),
        ),
    ]
