# Generated by Django 5.0.3 on 2024-05-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_course', '0004_trainingcourse_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='viewed_users',
        ),
        migrations.RemoveField(
            model_name='trainingcourse',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='trainingcourse',
            name='days_admission',
        ),
        migrations.RemoveField(
            model_name='trainingcourse',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='trainingcourse',
            name='time_is_fixed',
        ),
        migrations.AddField(
            model_name='lesson',
            name='link',
            field=models.URLField(blank=True, verbose_name='Ссылка на внешний сервис'),
        ),
    ]
