# Generated by Django 5.0.3 on 2024-05-18 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_course', '0005_remove_lesson_viewed_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='is_active',
        ),
    ]
