# Generated by Django 5.0.3 on 2024-06-12 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_course', '0009_questionanswer_questionnaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='lesson',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='training_course.lesson', verbose_name='К уроку'),
        ),
        migrations.AlterField(
            model_name='test',
            name='lesson',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='training_course.lesson', verbose_name='К уроку'),
        ),
    ]
